# Built-in features
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible' # Sensible
set -g @plugin 'tmux-plugins/tmux-yank' # Yank
set -g @plugin 'tmux-plugins/tmux-resurrect' # Resurrect
set -g @plugin 'tmux-plugins/tmux-continuum' # 4Continuum
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '60'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
